import { createElement } from '@lwc/engine-dom';
import ApplicationForm from 'c/applicationForm';

/**
 * Basic Jest test harness for the ApplicationForm LWC.
 *
 * Note: This is a starter test created by the Salesforce CLI. Extend it with
 * meaningful assertions if Jest tests are required for the assessment.
 */
describe('c-application-form', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    /** Placeholder test ensuring the component renders without throwing. */
    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-application-form', {
            is: ApplicationForm
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});